apiVersion: apps/v1
kind: Deployment
metadata:
 name: result
 namespace: eks-voting-app
 labels:
   app: result
spec:
 replicas: 1
 selector:
  matchLabels:
    app: result
 template:
  metadata:
   labels:
     app: result
  spec:
   containers:
    - name: result
      image: mshaikh911/result
      ports:
       - containerPort: 80
         name: result