apiVersion: v1
kind: Service
metadata:
 name: result
 namespace: eks-voting-app
 labels:
  app: result
spec:
  ports:
   - port: 5001
     targetPort: 80
     protocol: TCP
     name: result-service
  type: LoadBalancer
  selector:
   app: result