apiVersion: v1
kind: Service
metadata:
 name: vote
 namespace: eks-voting-app
 labels:
   apps: vote
spec:
  ports:
   - port: 5000
     targetPort: 80
     protocol: TCP
     name: vote-service
  type: LoadBalancer
  selector:
    app: vote